'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar de My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://timbradodp.expidetufactura.com.mx:8453/timbrado/TimbradoWS")>  _
        Public ReadOnly Property CochoSystem_mx_com_expidetufactura_timbradodp_TimbradoWSService() As String
            Get
                Return CType(Me("CochoSystem_mx_com_expidetufactura_timbradodp_TimbradoWSService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://pruebastimbrado.expidetufactura.com.mx:8443/preproduccion/TimbradoWS")>  _
        Public ReadOnly Property CochoSystem_mx_com_expidetufactura_pruebastimbrado_TimbradoWSService() As String
            Get
                Return CType(Me("CochoSystem_mx_com_expidetufactura_pruebastimbrado_TimbradoWSService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://timbrado.expidetufactura.com.mx:8443/PruebasNomina12TXT/TimbradoTXTServic"& _ 
            "e")>  _
        Public ReadOnly Property CochoSystem_mx_com_expidetufactura_timbradoP_TimbradoTXTService() As String
            Get
                Return CType(Me("CochoSystem_mx_com_expidetufactura_timbradoP_TimbradoTXTService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://cancelacion.expidetufactura.com.mx:8080/cancelacion/CancelacionProductivo")>  _
        Public ReadOnly Property CochoSystem_mx_com_expidetufactura_timbradoCancela_TimbradoTXTService() As String
            Get
                Return CType(Me("CochoSystem_mx_com_expidetufactura_timbradoCancela_TimbradoTXTService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://cancelacion.expidetufactura.com.mx:8080/cancelacion/CancelacionPruebas")>  _
        Public ReadOnly Property CochoSystem_mx_com_expidetufactura_cancelacion_CancelacionPruebas() As String
            Get
                Return CType(Me("CochoSystem_mx_com_expidetufactura_cancelacion_CancelacionPruebas"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://cancelacion.expidetufactura.com.mx:8080/cancelacion/CancelacionProductivo")>  _
        Public ReadOnly Property CochoSystem_mx_com_expidetufactura_cancelacion1_CancelacionProductivo() As String
            Get
                Return CType(Me("CochoSystem_mx_com_expidetufactura_cancelacion1_CancelacionProductivo"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.CochoSystem.My.MySettings
            Get
                Return Global.CochoSystem.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
